version: '3.8'

services:
  backend:
    build: ./ai-work-classification-engine
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=info
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-demo-key}
    volumes:
      - ./ai-work-classification-engine/config:/app/config
      - ./ai-work-classification-engine/data:/app/data
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    command: ["python", "api_server.py"]

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped

networks:
  default:
    driver: bridge
